config/routes.rb
Hr::Application.routes.draw do 

  devise_for :users

  resources :users
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
    	anonymus
    else
    	if user.role.name == "admin"
    		admin
    	elsif user.role.name == "manager"
    		manager
    	else
    		authenticated
    	end

    end 
end
    def anonymus
    end

    def authenticated
    	anonymus
    end

    def manager
    	authenticated
    end

    def admin
    	authenticated
    	can :manage, :all
    end
     
  
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
	
	def translated
	  I18n.t("roles."+self.name)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
 belongs_to :role
 devise :database_authenticatable, :rememberable, :trackable, :timeoutable
 # attr_accessor :username, :password, :password_confirmation, :remember_me
 validates :username, uniqueness: true
 validates_presence_of :username, :full_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  
  before_filter do
    resource = controller_path.singularize.gsub('/', '_').to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :password, :password_confirmation, :current_password) }
  end
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(user)
        root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	   unless user_signed_in?
	   	redirect_to new_user_session_path
	   end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    department = Department.find(user_params["department_id"])
    @user.department = department
    role = Role.find(user_params["role_id"])
    @user.role = role
    @user.password = "12345678"
    

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: t("common.saved_successfully") }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: t("common.saved_successfully") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :phone, :role_id, :department_id , :full_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert-box radius secondary"
    when :success then "alert-box radius success"
    when :error then "alert-box radius alert"
    when :alert then "alert-box radius alert"
    end
  end

  def page_title(title = nil)
    if title
      content_for(:page_title) { title }
    else
      content_for?(:page_title) ? content_for(:page_title) : 'HR'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
MAIN

app/views/layouts/_admin_sidebar.html.erb
		<li>
			<%= link_to users_path do %>
				<i class="fa fa-bars"></i>
				<%=t("admin.manage_users")%>
			<% end %>
		</li>
		
		<li>
			<%= link_to materials_path do %>
				<i class="fa fa-bars"></i>
				<%=t("admin.manage_materials")%>
			<% end %>
		</li>

		<li>
			<%= link_to products_path do %>
				<i class="fa fa-bars"></i>
				<%=t("admin.manage_products")%>
			<% end %>
		</li>


		

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div class="row">
    <div class="flash-messages small-12 column text-centered">
    <% [:notice, :error, :alert].each do |level| %>
      <% unless flash[level].blank? %>
      <div data-alert class="<%= flash_class level %>">
        <%= flash[level] %><a href="#" class="close">&times;</a>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="column large-12">
  
  <div class="">
    <div class="large-8 medium-8 columns">
     
      <p class="copyright">&#169; 2014 HR</p>
    </div>

  </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "HR" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= google_webfonts_init({ google: ['Open Sans', 'Montserrat'] }) %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>  
</head>

app/views/layouts/_header.html.erb
<%unless current_user.nil?%>
<div class="fixed">

  <nav class="top-bar" data-topbar>
    <ul class="title-area">
    <li class="name">
      <h1><%=link_to(t("common.home"),root_path) %></h1>
    </li>
    
  	</ul>
  	<section class="top-bar-section">
  		<ul class="left">
      		<li><%= link_to t("common.sign_out"), destroy_user_session_path , :method => "delete"%></li>
    	</ul>
  		
  	</section>
  </nav>

</div>
<%end%>

app/views/layouts/_sidebar.html.erb
<div class="row">
	<div class="side-bar side-nav">
		<%if current_user.role.name == "admin"%>
			<%= render "layouts/admin_sidebar"%>
		<%end%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render partial: 'layouts/head' %>
  <body>
  	<%= render partial: 'layouts/header' %>
    <div class="content contentWrapper">
      <%= render partial: 'layouts/flash' %>
      <% unless current_user.blank? %>
        <div class="mainContent">
          <div class="row">
              <%= yield %>
            
          </div>
        </div>
      <% else %>
          <%= yield %>
      <% end %>
      <div class="row"></div>
    </div>


    <%= render partial: 'layouts/footer' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:data => {:abide => ''}}) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
	
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :username, t("admin.users.username") %>
	<br>
	<%= f.text_field :username , :required => ''  %>
	<small class="error"><%=t("common.errors.required")%></small>
</div>

<div class="field">
	<%= f.label :full_name, t("admin.users.full_name") %>
	<br>
	<%= f.text_field :full_name , :required => ''  %>
	<small class="error"><%=t("common.errors.required")%></small>
</div>

<div class="field">
	<%= f.label :email, t("admin.users.email") %>
	<br>
	<%= f.email_field :email, :pattern => "email" %>
	<small class="error"><%=t("common.errors.pattern")%></small>
</div>

<div class="field">
	<%= f.label :phone, t("admin.users.phone") %>
	<br>
	<%= f.text_field :phone %>
</div>

<div class="field">
	<%= f.label :role_id, t("admin.users.role") %>
	<br>
	<%= f.select :role_id, options_from_collection_for_select(Role.all, "id", "translated",@user.role_id) %>
</div>

<div class="field">
	<%= f.label :department_id, t("admin.users.department") %>
	<br>
	<%= f.select :department_id, options_from_collection_for_select(Department.all, "id", "translated",@user.department_id) %>
</div>
<div class="actions">
	<%= f.submit t("admin.users.save"), :class => "tiny button left" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1><%=t("admin.users.edit")%></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1><%= t("admin.manage_users")%></h1>

<table>
	<thead>
		<tr>
			<th width="200"><%=t("admin.users.full_name")%></th>
			<th width="100"><%=t("admin.users.phone")%></th>
			<th width="200"><%=t("admin.users.email")%></th>
			<th><%=t("admin.users.department")%></th>
			<th></th>
			
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<%unless user.id == current_user.id%>
		<tr>
			<td><%= user.full_name %></td>
			<td><%= user.phone %></td>
			<td><%= user.email %></td>
			<td><%= t("departments."+user.department.name) %></td>
			<td><%= link_to t("common.edit"), edit_user_path(user) %></td>
			
		</tr>
		<%end%>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to t("admin.users.new"), new_user_path %>

app/views/users/new.html.erb
<h1><%=t("admin.users.new")%></h1>
<h3><%=t("admin.users.default_password")%></h3>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>